config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#homepage'
  get 'about', to: 'pages#about'
  get 'directories', to: 'pages#directories'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length:{ minimum: 3, maximum: 50 }
  validates :description, presence: true, length:{ minimum: 3, maximum: 300 }
  validates :post, presence: true, length:{ minimum: 3, maximum: 2000 }
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false}, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /(\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z)?(@zappistore.com)/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user
  before_action :require_same_user, only: [:destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 20)
  end
  
 
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Post was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  
  def update
    if @article.update(article_params)
      flash[:success] = "Post was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Post was successfully deleted"
    redirect_to articles_path
  end
  
  private
    def set_article
    @article = Article.find(params[:id])
    end
    
    def article_params
    params.require(:article).permit(:title, :description, :post, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only delete your Posts"
        redirect_to root_path
      end
    end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 before_action :require_user
 before_action :require_admin, only: [:destroy]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 20)
  end
  
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
   def edit
     @category = Category.find(params[:id])
   end
  

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end


  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 20)
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] = "Category was successfully deleted"
    redirect_to categories_path
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  
# Only admins can delete categories 
  def require_admin
   if !current_user.admin?
      flash[:danger] = "Only an Admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pages
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have succesfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid email and/or password, try again."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_user, only: [:index, :edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Zappi Ninjas #{@user.username}"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
      if @user.update(user_params)
        flash[:success] = "Account updated successfully"
        redirect_to user_path
      else
        render 'edit'
      end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by the user have been deleted"
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account!"
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only an Admin can perform that action"
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <div style="word-wrap: break-word; overflow-y: hidden;">
            <%= simple_format(article.description) %>
          </div>
        </div>
        <% if article.categories.any? %>
          <div class="article-actions">
            <p>Categories: <%= render article.categories %></p>
          </div>
        <% end %>
        <!-- this next if logged_in is to make sure that if for some reason-->
        <!-- a user that is not logged can see the post then at least that person cant delete or edit -->
        <% if logged_in? %>
          <div class="article-actions">
            <%= link_to "Edit this post", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <% if current_user == article.user || current_user.admin? %>
              <%= link_to "Delete this post", article_path(article), method: :delete, 
                                                                     data: { confirm: "Are you sure you want to delete this post?"}, 
                                                                    class: "btn btn-xs btn-danger" %>
            <% end %>
            <div class="article-meta-details">
              <small>
                Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          <% end %>  
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of the Wiki post", autofocus: true %>
          </div>
        </div>
        <div class ="form-group">
          <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>  
        </div>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Description of the Wiki post" %>
          </div>
        </div>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :post %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :post, rows: 50, class: "form-control", placeholder: "Write the post here" %>
          </div>
        </div>
        <div class ="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to Wiki", articles_path %> ]
    </div>
  
  </div>
</div>  

app/views/articles/edit.html.erb
<h1><center>Edit existing Wiki post</h1></center>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all Wiki posts</h1>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1><center>New Wiki post</h1></center>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
  <div class="well col-xs-8 col-xs-offset-2">
     <% if @article.user %>
     <ul class="listing">
      <div class align="center">
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by:</li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li><small>
              <%= pluralize(@article.user.articles.count, "post") if @article.user.articles %>
            </small></li>
          </div>
        </div>
      </div>
    </ul>
    <% end %>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>
    <h4 align="center" class="description"><strong>Description:</strong></h4>
    <hr>
      <div style="word-wrap: break-word; overflow-y: hidden;">
        <%= simple_format(@article.description) %>
      </div>
    </hr>
    <hr>
    <h4 align="center" class="post"><strong>Post:</strong></h4>
      <div style="word-wrap: break-word; overflow-y: hidden;">
        <%= simple_format(@article.post) %>
      </div>
    </hr>
    <div class="article-actions">
    <!-- this next if logged_in is to make sure that if for some reason-->
    <!-- that is not logged can see the post then at least that person cant delete or edit -->
    <% if logged_in? %>
      <%= link_to "Edit this post", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <% if current_user == @article.user || current_user.admin? %>
        <%= link_to "Delete this post", article_path(@article), method: :delete, 
                                                                  data: { confirm: "Are you sure you want to delete this post?"}, 
                                                                  class: "btn btn-xs btn-danger" %>
      <% end %>
    <% end %>
    <%= link_to "Back to Wiki", articles_path, class: "btn btn-xs btn-success" %>
    </div>
  </div>  
  
    

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>&nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class ="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
    </div>
    <div class ="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel and return the categries page", categories_path %>]
</div>

app/views/categories/edit.html.erb
<h1><center>Edit category name</h1></center>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">listing all categories</h1>
<div align="center">
  <%= will_paginate %>
  <% Category.all.sort_by(&:name).each do |category| %> 
    <ul class="listing">
      <div class="row">
        <div class="well col-md-8 col-md-offset-2">
          <li class="category-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
          <!-- this next if logged_in is to make sure that if for some reason-->
          <!-- a user that is not logged can see the post then at least that person cant delete or edit -->
          <% if logged_in? %>
            <div class="category-actions">
              <%= link_to "Edit this category", edit_category_path(category), class: "btn btn-xs btn-primary" %>
              <% if current_user.admin? %>
                <%= link_to "Delete this category", category_path(category), method: :delete, 
                                                                       data: { confirm: " Are you sure you want to delete this category? The Category will be removed from created posts!!"}, 
                                                                      class: "btn btn-xs btn-danger" %>
              <% end %>
              <div class="category-meta-details">
                <small>
                  <%= time_ago_in_words(category.created_at) %> ago,
                  last updated: <%= time_ago_in_words(category.updated_at) %> ago
                </small>
              </div>
            </div>
          <% end %> 
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div> 

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
  <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  </div>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer"
    <small>
     Copyright &copy; <a href="https://www.zappistore.com">Zappi Ninjas</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to"About", about_path %></li>
      </ul>
    </nav>
   </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
   <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data dismiss="alert">&#215;</a>
     <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
   </div>
  <% end %>
 </div>
</div>

app/views/layouts/_navigation.html.erb
<!-- this is the ZappiNinjas button -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Zappi Ninjas", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- this is the wiki/and actions buttons -->
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Wiki<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All posts", articles_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New post", new_article_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <!-- this is the category/and actions buttons -->
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Category", new_category_path %></li>
            </ul>
          </li>
          <li><%= link_to "Directories", directories_path %></li>
        <% end %>
      </ul>
      <!-- this is the search and submit button -->
      <form class="navbar-form navbar-left">
        <% if logged_in? %>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search Post">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
         <% end %>
      </form>
      <!-- this is the account button -->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zappi-Ninjas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
    
<h4><center> heyhey </center></h4>


</head>
<body>
  
<% if !logged_in? %>
  <div class="row">
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="http://inspiringhealth.org.uk/wp-content/uploads/2017/07/3d-abstract_other_just-relax_44940.jpg" alt="UPS" style="width:250px;height:250px;" >
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'ivan1.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'jq.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
  </div>
  <!-- Did this duplicated thing to show only 3 thumbnails at the top and 2 under them -->
  <div class="row">
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'mike1.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'tanner1.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
  </div>
  
<% else %>

  <div class="row">
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'liam2.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'ivan2.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'jq2.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
  </div>
  <!-- Did this duplicated thing to show only 3 thumbnails at the top and 2 under them -->
  <div class="row">
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="http://inspiringhealth.org.uk/wp-content/uploads/2017/07/3d-abstract_other_just-relax_44940.jpg" alt="UPS" style="width:250px;height:250px;">
      </a>
    </div>
    <div class="col-xs-5 col-md-3">
      <a href="#" class="thumbnail">
        <img src="<%= asset_path( 'tanner2.png' ) %>" style="width:250px;height:250px;" />
      </a>
    </div>
  </div>
<% end %>

</body>
</html>

app/views/pages/directories.html.erb
<h4><center> links here </center></h4>

app/views/pages/homepage.html.erb
<h4><center>Need to write something here</center></h4>

<div class="jumbotron">
</div>
 





    

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibided this form from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :username %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
          </div>
        </div>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :email %>
          </div>
          <div class="col-sm-8">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
          </div>
        </div>
        <div class ="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :password %>
          </div>
          <div class="col-sm-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>
        <% if logged_in? and current_user.admin?%>
          <div class="form-check">
            <div class="control-label col-sm-2">
                  <%= f.label "Admin" %> 
                  <%= f.check_box :admin %>
            </div>
          </div>
        <% end %>  
        <div class ="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: 'btn btn-primary') %>
          </div>
        </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel and return to main page", root_path %>]
    </div>
  </div>
</div>  

app/views/users/edit.html.erb
<h1 align="center">Edit account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All users</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small>
            <%= pluralize(user.articles.count, "post") if user.articles %>
            <% if logged_in? and current_user.admin? %>
              <li><%= link_to "Delete this user", user_path(user), method: :delete, 
                  data: { confirm: "Are you sure you want to delete the user and all the articles?"} %></li>
            <% end %>
          </small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 align="center">Sign up for Zappi Ninjas Wiki</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"><%= @user.username %>'s</h1>

<% if @user.admin?  %>
  <h5 align="center">Account type: Admin</h5>
<% else %>
  <h5 align="center">Account type: User</h5>
<% end %>

 <!-- the following if's will enable the option to edit user or users(if admin) profile -->
<% if current_user.admin? and current_user != @user %>
  <h5 align="center"><%= link_to "Edit user account", edit_user_path(@user.id) %></h5>
<% end %>
<% if current_user == @user %>
  <h5 align="center"><%= link_to "Edit your account", edit_user_path(current_user) %></h5>
<% end %>



<div class="row">
  <div class align="center", "col-md-4 col-md-offset-4">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s posts</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>